### ISSUE TITLE
It does not work 

### ISSUE THREAD

**Issue by Conny64** [lpaulsen93/dw-plugin-prettyPhoto#3]
In the current version Release 2020-07-29 "Hogfather", the plugin doesn't work.

**Comment by ssahara** [comment]
I am not good at javascript, however it seems there is a bug in **js/jquery.prettyPhoto.js** file. I will try to fix `size()` exception by replacing it with 'length` property.

**Comment by ssahara** [comment]
Updated. The DokuWIki config **defer_js** should need to be off.
